name: Collection Docs
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - test/pr/*
    tags:
      - v*

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main

  publish-docs:
    permissions:
      contents: write
    name: Publish to GH Pages
    needs: [build-docs]
    uses: briantist/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@publish/gh-pages
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      action: ${{ (github.event.action == 'closed' || needs.build-docs.outputs.changed != 'true') && 'teardown' || 'publish' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
